///////////////////////////////////////////////////
// This file is generated by build-interfaces.ts //
///////////////////////////////////////////////////

import {
  LaraJoinPoint,
  registerJoinpointMapper,
  wrapJoinPoint,
  unwrapJoinPoint,
  InsertPosition,
} from "@specs-feup/lara/api/LaraJoinPoint.ts";

type PrivateMapper = {
  "Joinpoint": typeof Joinpoint,
  "Program": typeof Program,
  "FileJp": typeof FileJp,
  "Statement": typeof Statement,
  "Expr": typeof Expr,
  "BinaryOperator": typeof BinaryOperator,
  "ExecutableStatement": typeof ExecutableStatement,
  "ActionStatement": typeof ActionStatement,
  "AssignmentStatement": typeof AssignmentStatement,
  "Designator": typeof Designator,
  "DataRef": typeof DataRef,
  "Literal": typeof Literal,
  "IntLiteral": typeof IntLiteral,
  "StringLiteral": typeof StringLiteral,
  "RealLiteral": typeof RealLiteral,
  "DoStatement": typeof DoStatement,
  "LoopControl": typeof LoopControl,
  "RangeLoopControl": typeof RangeLoopControl,
  "StatementBlock": typeof StatementBlock,
  "Execution": typeof Execution,
  "Specification": typeof Specification,
  "ArraySubscriptExpr": typeof ArraySubscriptExpr,
  "CompilerDirective": typeof CompilerDirective,
  "NameValue": typeof NameValue,
  "OmpConstruct": typeof OmpConstruct,
  "OmpBlockConstruct": typeof OmpBlockConstruct,
  "OmpLoopConstruct": typeof OmpLoopConstruct,
  "OmpClause": typeof OmpClause,
  "OmpDataSharingClause": typeof OmpDataSharingClause,
  "OmpReductionClause": typeof OmpReductionClause,
  "OmpOrderedClause": typeof OmpOrderedClause,
  "UseStatement": typeof UseStatement,
  "ProgramUnit": typeof ProgramUnit,
  "MainProgram": typeof MainProgram,
  "Subroutine": typeof Subroutine,
  "SpecificationStatement": typeof SpecificationStatement,
  "TypeDeclarationStatement": typeof TypeDeclarationStatement,
  "AttributeSpecifier": typeof AttributeSpecifier,
  "KeywordAttributeSpecifier": typeof KeywordAttributeSpecifier,
  "ParameterKeyword": typeof ParameterKeyword,
  "FortranDecl": typeof FortranDecl,
  "EntityDecl": typeof EntityDecl,
  "Initialization": typeof Initialization,
  "ExprInitialization": typeof ExprInitialization,
  "IfStatement": typeof IfStatement,
  "IfConstruct": typeof IfConstruct,
  "IfThenBlock": typeof IfThenBlock,
  "IfThenStatement": typeof IfThenStatement,
  "ElseIfBlock": typeof ElseIfBlock,
  "ElseIfStatement": typeof ElseIfStatement,
  "ElseBlock": typeof ElseBlock,
  "SectionSubscript": typeof SectionSubscript,
  "Subscript": typeof Subscript,
};

type DefaultAttributeMap = {
  FileJp: "name",
}

export class Joinpoint extends LaraJoinPoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * The children of this join point, ignoring null nodes
   */
  get children(): Joinpoint[] { return wrapJoinPoint(this._javaObject.children()) }
  /**
   * All descendants of this join point
   */
  get descendants(): Joinpoint[] { return wrapJoinPoint(this._javaObject.descendants()) }
  /**
   * Returns the index of this join point in relation to its parent
   */
  get indexOfSelf(): number { return wrapJoinPoint(this._javaObject.indexOfSelf()) }
  /**
   * Returns the node that came before this node, or undefined if there is none
   */
  get leftJp(): Joinpoint { return wrapJoinPoint(this._javaObject.leftJp()) }
  /**
   * Returns the parent node in the AST, or undefined if it is the root node
   */
  get parent(): Joinpoint { return wrapJoinPoint(this._javaObject.parent()) }
  /**
   * Returns the node that comes after this node, or undefined if there is none
   */
  get rightJp(): Joinpoint { return wrapJoinPoint(this._javaObject.rightJp()) }
  /**
   * Returns the 'program' join point
   */
  get root(): Program { return wrapJoinPoint(this._javaObject.root()) }
  /**
   * The scope nodes of this join point
   */
  get scopeNodes(): Joinpoint[] { return wrapJoinPoint(this._javaObject.scopeNodes()) }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  compareNodes(aJoinPoint: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.compareNodes(unwrapJoinPoint(aJoinPoint))); }
  /**
   * True if the given node is a descendant of this node
   */
  contains(jp: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.contains(unwrapJoinPoint(jp))); }
  /**
   * Performs a copy of the node and its children, but not of the nodes in its fields
   */
  copy(): Joinpoint { return wrapJoinPoint(this._javaObject.copy()); }
  /**
   * Performs a copy of the node and its children, including the nodes in their fields (only the first level of field nodes, this function is not recursive)
   */
  deepCopy(): Joinpoint { return wrapJoinPoint(this._javaObject.deepCopy()); }
  /**
   * Removes node associated to the joinpoint from the AST
   */
  detach(): Joinpoint { return wrapJoinPoint(this._javaObject.detach()); }
  /**
   * Looks for an ancestor joinpoint name, walking back on the AST
   */
  getAncestor(type: string): Joinpoint { return wrapJoinPoint(this._javaObject.getAncestor(unwrapJoinPoint(type))); }
  insert(position: InsertPosition, code: string): Joinpoint[];
  insert(position: InsertPosition, joinpoint: Joinpoint): Joinpoint[];
  insert(p1: InsertPosition, p2: string | Joinpoint): Joinpoint[] { return wrapJoinPoint(this._javaObject.insert(unwrapJoinPoint(p1), unwrapJoinPoint(p2))); }
  /**
   * Inserts the given join point after this join point
   */
  insertAfter(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a string
   */
  insertAfter(code: string): Joinpoint;
  /**
   * Inserts the given join point after this join point
   */
  insertAfter(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertAfter(unwrapJoinPoint(p1))); }
  /**
   * Inserts the given join point before this join point
   */
  insertBefore(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a string
   */
  insertBefore(node: string): Joinpoint;
  /**
   * Inserts the given join point before this join point
   */
  insertBefore(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertBefore(unwrapJoinPoint(p1))); }
  /**
   * Replaces this node with the given node
   */
  replaceWith(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a list of nodes
   */
  replaceWith(node: Joinpoint[]): Joinpoint;
  /**
   * Replaces this node with the given node
   */
  replaceWith(p1: Joinpoint | Joinpoint[]): Joinpoint { return wrapJoinPoint(this._javaObject.replaceWith(unwrapJoinPoint(p1))); }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  same(other: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.same(unwrapJoinPoint(other))); }
}

  /**
   * Represents the complete program and is the top-most join point in the hierarchy
   */
export class Program extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents a source file (e.g., .f90)
   */
export class FileJp extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: "name",
  };
  /**
   * The name of the folder
   */
  get foldername(): string { return wrapJoinPoint(this._javaObject.foldername()) }
  /**
   * The name of the file
   */
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

  /**
   * Represents a Fortran statement
   */
export class Statement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get isFirst(): boolean { return wrapJoinPoint(this._javaObject.isFirst()) }
  get isLast(): boolean { return wrapJoinPoint(this._javaObject.isLast()) }
}

  /**
   * Represents an expression
   */
export class Expr extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents a binary operation
   */
export class BinaryOperator extends Expr {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get kind(): BinaryOperatorKind { return wrapJoinPoint(this._javaObject.kind()) }
  get left(): Expr { return wrapJoinPoint(this._javaObject.left()) }
  set left(value: Expr) { this._javaObject.setLeft(unwrapJoinPoint(value)); }
  get right(): Expr { return wrapJoinPoint(this._javaObject.right()) }
  set right(value: Expr) { this._javaObject.setRight(unwrapJoinPoint(value)); }
  /**
   * Sets the left-hand side of the operation
   */
  setLeft(lhs: Expr): void { return wrapJoinPoint(this._javaObject.setLeft(unwrapJoinPoint(lhs))); }
  /**
   * Sets the right-hand side of the operation
   */
  setRight(rhs: Expr): void { return wrapJoinPoint(this._javaObject.setRight(unwrapJoinPoint(rhs))); }
}

  /**
   * Represents an executable statement
   */
export class ExecutableStatement extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents an action statement
   */
export class ActionStatement extends ExecutableStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents an assignment statement
   */
export class AssignmentStatement extends ActionStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get expr(): Expr { return wrapJoinPoint(this._javaObject.expr()) }
  get variable(): DataRef { return wrapJoinPoint(this._javaObject.variable()) }
}

  /**
   * Represents a designator
   */
export class Designator extends Expr {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents a data reference
   */
export class DataRef extends Designator {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

  /**
   * Represents a literal
   */
export class Literal extends Expr {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get literal(): string { return wrapJoinPoint(this._javaObject.literal()) }
}

export class IntLiteral extends Literal {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class StringLiteral extends Literal {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class RealLiteral extends Literal {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents a do loop
   */
export class DoStatement extends ExecutableStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get body(): Execution { return wrapJoinPoint(this._javaObject.body()) }
  get control(): LoopControl { return wrapJoinPoint(this._javaObject.control()) }
  get kind(): DoKind { return wrapJoinPoint(this._javaObject.kind()) }
  /**
   * Performs a copy of the do statement, including its controls, but not the body
   */
  copyScope(): DoStatement { return wrapJoinPoint(this._javaObject.copyScope()); }
  /**
   * Returns true if the given do statement has the same loop control as this do statement
   */
  sameScope(loop: DoStatement): boolean { return wrapJoinPoint(this._javaObject.sameScope(unwrapJoinPoint(loop))); }
}

  /**
   * Represents the loop control structure, with specialized subclasses for different loop kinds
   */
export class LoopControl extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class RangeLoopControl extends LoopControl {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get lower(): Expr { return wrapJoinPoint(this._javaObject.lower()) }
  get step(): Expr { return wrapJoinPoint(this._javaObject.step()) }
  set step(value: Expr) { this._javaObject.setStep(unwrapJoinPoint(value)); }
  get upper(): Expr { return wrapJoinPoint(this._javaObject.upper()) }
  set upper(value: Expr) { this._javaObject.setUpper(unwrapJoinPoint(value)); }
  get var(): DataRef { return wrapJoinPoint(this._javaObject.var()) }
  setStep(step: Expr): void { return wrapJoinPoint(this._javaObject.setStep(unwrapJoinPoint(step))); }
  setUpper(upper: Expr): void { return wrapJoinPoint(this._javaObject.setUpper(unwrapJoinPoint(upper))); }
}

export class StatementBlock extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get stmts(): Statement[] { return wrapJoinPoint(this._javaObject.stmts()) }
}

export class Execution extends StatementBlock {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get executableStmts(): ExecutableStatement[] { return wrapJoinPoint(this._javaObject.executableStmts()) }
  insertBegin(stmt: ExecutableStatement): void { return wrapJoinPoint(this._javaObject.insertBegin(unwrapJoinPoint(stmt))); }
  insertEnd(stmt: ExecutableStatement): void { return wrapJoinPoint(this._javaObject.insertEnd(unwrapJoinPoint(stmt))); }
}

export class Specification extends StatementBlock {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get specificationStmts(): SpecificationStatement[] { return wrapJoinPoint(this._javaObject.specificationStmts()) }
  /**
   * Adds a UseStmt to a specification part. The statement is inserted at the beginning.
   */
  addUseStmt(stmt: UseStatement): void { return wrapJoinPoint(this._javaObject.addUseStmt(unwrapJoinPoint(stmt))); }
}

  /**
   * Represents an access to one (or several) elements of an array
   */
export class ArraySubscriptExpr extends DataRef {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get subscripts(): SectionSubscript[] { return wrapJoinPoint(this._javaObject.subscripts()) }
  get var(): DataRef { return wrapJoinPoint(this._javaObject.var()) }
}

export class CompilerDirective extends ExecutableStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * Returns the directive's contents as a string
   */
  get directiveString(): string { return wrapJoinPoint(this._javaObject.directiveString()) }
  get pairs(): NameValue[] { return wrapJoinPoint(this._javaObject.pairs()) }
}

  /**
   * Represents a name/value pair in a compiler directive
   */
export class NameValue extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

  /**
   * Represents a generic OpenMP construct
   */
export class OmpConstruct extends ExecutableStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get clauses(): OmpClause[] { return wrapJoinPoint(this._javaObject.clauses()) }
  set clauses(value: OmpClause[]) { this._javaObject.setClauses(unwrapJoinPoint(value)); }
  /**
   * Sets the construct's clauses
   */
  setClauses(clauses: OmpClause[]): void { return wrapJoinPoint(this._javaObject.setClauses(unwrapJoinPoint(clauses))); }
  setDirective(directive: string): void { return wrapJoinPoint(this._javaObject.setDirective(unwrapJoinPoint(directive))); }
}

  /**
   * Represents an OpenMP block construct (such as parallel or task)
   */
export class OmpBlockConstruct extends OmpConstruct {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  setBody(body: Execution): void { return wrapJoinPoint(this._javaObject.setBody(unwrapJoinPoint(body))); }
}

  /**
   * Represents an OpenMP loop construct (such as do or do parallel)
   */
export class OmpLoopConstruct extends OmpConstruct {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  setLoop(loop: DoStatement): void { return wrapJoinPoint(this._javaObject.setLoop(unwrapJoinPoint(loop))); }
}

  /**
   * Represents an OpenMP clause
   */
export class OmpClause extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represents an OpenMP datasharing clause (public, private, ...)
   */
export class OmpDataSharingClause extends OmpClause {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class OmpReductionClause extends OmpClause {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class OmpOrderedClause extends OmpClause {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class UseStatement extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get moduleName(): string { return wrapJoinPoint(this._javaObject.moduleName()) }
}

export class ProgramUnit extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * Returns the unit's specification part
   */
  get specification(): Specification { return wrapJoinPoint(this._javaObject.specification()) }
}

export class MainProgram extends ProgramUnit {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class Subroutine extends ProgramUnit {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get moduleName(): string { return wrapJoinPoint(this._javaObject.moduleName()) }
}

export class SpecificationStatement extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class TypeDeclarationStatement extends SpecificationStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get attrs(): AttributeSpecifier[] { return wrapJoinPoint(this._javaObject.attrs()) }
  get decls(): EntityDecl[] { return wrapJoinPoint(this._javaObject.decls()) }
}

export class AttributeSpecifier extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class KeywordAttributeSpecifier extends AttributeSpecifier {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class ParameterKeyword extends KeywordAttributeSpecifier {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class FortranDecl extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class EntityDecl extends FortranDecl {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

export class Initialization extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

export class ExprInitialization extends Initialization {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get expr(): Expr { return wrapJoinPoint(this._javaObject.expr()) }
}

export class IfStatement extends ActionStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get condition(): Expr { return wrapJoinPoint(this._javaObject.condition()) }
  get statement(): ActionStatement { return wrapJoinPoint(this._javaObject.statement()) }
}

  /**
   * Represents the root of an if construct
   */
export class IfConstruct extends ExecutableStatement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get elseBlock(): ElseBlock { return wrapJoinPoint(this._javaObject.elseBlock()) }
  get elseIfBlocks(): ElseIfBlock[] { return wrapJoinPoint(this._javaObject.elseIfBlocks()) }
  get ifThenBlock(): IfThenBlock { return wrapJoinPoint(this._javaObject.ifThenBlock()) }
}

  /**
   * Represents the first block of an if construct
   */
export class IfThenBlock extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get body(): StatementBlock { return wrapJoinPoint(this._javaObject.body()) }
  get header(): IfThenStatement { return wrapJoinPoint(this._javaObject.header()) }
}

  /**
   * Represents the header of an 'if then' block
   */
export class IfThenStatement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get condition(): Expr { return wrapJoinPoint(this._javaObject.condition()) }
}

  /**
   * Represents the optional 'else if' blocks of an if construct
   */
export class ElseIfBlock extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get body(): StatementBlock { return wrapJoinPoint(this._javaObject.body()) }
  get header(): ElseIfStatement { return wrapJoinPoint(this._javaObject.header()) }
}

  /**
   * Represents the header of an 'else if' block
   */
export class ElseIfStatement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get condition(): Expr { return wrapJoinPoint(this._javaObject.condition()) }
}

  /**
   * Represents the optional 'else' block of an if construct
   */
export class ElseBlock extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get body(): StatementBlock { return wrapJoinPoint(this._javaObject.body()) }
}

  /**
   * Represent a generic subscript for an array
   */
export class SectionSubscript extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Represent an integer subscript for an array
   */
export class Subscript extends SectionSubscript {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get expr(): Expr { return wrapJoinPoint(this._javaObject.expr()) }
}

/**
 * This is supposed to be an enum, but Node.js v25 does bot support TS' enums, only erasable-syntax.
 * Revert to an enum when Node.js supports it, or when we move to a different engine that supports it.
 * This and the "type" declaration below.
 */
export const DoKind = {
  while: "while",
  range: "range",
  concurrent: "concurrent",
} as const;
export type DoKind = typeof DoKind[keyof typeof DoKind];

/**
 * This is supposed to be an enum, but Node.js v25 does bot support TS' enums, only erasable-syntax.
 * Revert to an enum when Node.js supports it, or when we move to a different engine that supports it.
 * This and the "type" declaration below.
 */
export const BinaryOperatorKind = {
  ADD: "ADD",
  SUBTRACT: "SUBTRACT",
  MULTIPLY: "MULTIPLY",
  DIVIDE: "DIVIDE",
  POWER: "POWER",
  LT: "LT",
  LE: "LE",
  GT: "GT",
  GE: "GE",
  EQ: "EQ",
  NE: "NE",
  AND: "AND",
} as const;
export type BinaryOperatorKind = typeof BinaryOperatorKind[keyof typeof BinaryOperatorKind];

const JoinpointMapper = {
  joinpoint: Joinpoint,
  program: Program,
  file: FileJp,
  statement: Statement,
  expr: Expr,
  binaryOperator: BinaryOperator,
  executableStatement: ExecutableStatement,
  actionStatement: ActionStatement,
  assignmentStatement: AssignmentStatement,
  designator: Designator,
  dataRef: DataRef,
  literal: Literal,
  intLiteral: IntLiteral,
  stringLiteral: StringLiteral,
  realLiteral: RealLiteral,
  doStatement: DoStatement,
  loopControl: LoopControl,
  rangeLoopControl: RangeLoopControl,
  statementBlock: StatementBlock,
  execution: Execution,
  specification: Specification,
  arraySubscriptExpr: ArraySubscriptExpr,
  compilerDirective: CompilerDirective,
  nameValue: NameValue,
  ompConstruct: OmpConstruct,
  ompBlockConstruct: OmpBlockConstruct,
  ompLoopConstruct: OmpLoopConstruct,
  ompClause: OmpClause,
  ompDataSharingClause: OmpDataSharingClause,
  ompReductionClause: OmpReductionClause,
  ompOrderedClause: OmpOrderedClause,
  useStatement: UseStatement,
  programUnit: ProgramUnit,
  mainProgram: MainProgram,
  subroutine: Subroutine,
  specificationStatement: SpecificationStatement,
  typeDeclarationStatement: TypeDeclarationStatement,
  attributeSpecifier: AttributeSpecifier,
  keywordAttributeSpecifier: KeywordAttributeSpecifier,
  parameterKeyword: ParameterKeyword,
  fortranDecl: FortranDecl,
  entityDecl: EntityDecl,
  initialization: Initialization,
  exprInitialization: ExprInitialization,
  ifStatement: IfStatement,
  ifConstruct: IfConstruct,
  ifThenBlock: IfThenBlock,
  ifThenStatement: IfThenStatement,
  elseIfBlock: ElseIfBlock,
  elseIfStatement: ElseIfStatement,
  elseBlock: ElseBlock,
  sectionSubscript: SectionSubscript,
  subscript: Subscript,
};

let registered = false;
if (!registered) {
  registerJoinpointMapper(JoinpointMapper);
  registered = true;
}

